services:
  # Web Service
  - type: web
    name: olx-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: OLX
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: olx-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: olx-database
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: olx-database
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: olx-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: olx-database
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      
  # Database Service
  - type: pserv
    name: olx-database
    plan: free
    ipAllowList: []
    databaseName: olx
    user: olx_user

