services:
  # Web Service
  - type: web
    name: olx-app
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan view:cache
      php artisan route:cache
      php artisan migrate --force
      php artisan db:seed --force
    startCommand: php artisan run --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        fromDatabase:
          key: APP_KEY
      - key: DB_HOST
        fromDatabase:
          key: DB_HOST
      - key: DB_NAME
        fromDatabase:
          key: DB_NAME
      - key: DB_USER
        fromDatabase:
          key: DB_USER
      - key: DB_PASSWORD
        fromDatabase:
          key: DB_PASSWORD
      
  # Database Service
  - type: pservice
    name: olx-database
    plan: free
    databaseName: olx
    user: olx_user
